# Generated by Django 4.1.7 on 2023-03-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title', max_length=256, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10000, verbose_name='Price')),
                ('zipcode', models.CharField(help_text='Product zipcode', max_length=256, verbose_name='Zipcode')),
                ('seller', models.CharField(help_text='Product seller', max_length=256, verbose_name='Seller')),
                ('thumbnailHd', models.CharField(help_text='Product thumbnailHd', max_length=256, verbose_name='ThumbnailHd')),
                ('date', models.DateField(help_text='Product date', verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='History value', max_digits=10000, verbose_name='Value')),
                ('date', models.DateField(help_text='History date', verbose_name='Date')),
                ('cliente_id', models.ForeignKey(help_text='Cliente_id', on_delete=django.db.models.deletion.CASCADE, to='store.client', verbose_name='Cliente_id')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_to_pay', models.DecimalField(decimal_places=2, help_text='Buy total_to_pay', max_digits=10000, verbose_name='Total_to_pay')),
                ('card_number', models.CharField(help_text='Buy card_number', max_length=256, verbose_name='Card_number')),
                ('value', models.DecimalField(decimal_places=2, help_text='Buy value', max_digits=10000, verbose_name='Value')),
                ('cvv', models.CharField(help_text='Buy cvv', max_length=3, verbose_name='Cvv')),
                ('card_holder_name', models.CharField(help_text='Buy card_holder_name', max_length=256, verbose_name='Card_holder_name')),
                ('exp_date', models.CharField(help_text='Buy exp_date', max_length=4, verbose_name='Exp_date')),
                ('cliente_id', models.ForeignKey(help_text='Cliente_id', on_delete=django.db.models.deletion.CASCADE, to='store.client', verbose_name='Cliente_id')),
            ],
        ),
    ]
