# Generated by Django 4.1.7 on 2023-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='total_to_pay',
        ),
        migrations.AddField(
            model_name='client',
            name='total_to_pay',
            field=models.DecimalField(decimal_places=2, help_text='Total to Pay', max_digits=10000, null=True, verbose_name='Total_to_pay'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='card_holder_name',
            field=models.CharField(help_text='Name of card holder', max_length=256, verbose_name='Card_holder_name'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='card_number',
            field=models.CharField(help_text='Number of Credit Card', max_length=256, verbose_name='Card_number'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='cvv',
            field=models.CharField(help_text='CVV Security Code of Credit Cart', max_length=3, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='exp_date',
            field=models.CharField(help_text='Expiration Date of card', max_length=4, verbose_name='Exp_date'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Value', max_digits=10000, verbose_name='Value'),
        ),
    ]
