# Generated by Django 4.1.7 on 2023-03-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_buy_total_to_pay_client_total_to_pay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='cliente_name',
        ),
    ]
