# Generated by Django 4.1.7 on 2023-03-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_history_date_remove_history_value_buy_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='card_number',
            field=models.CharField(help_text='Card_number', max_length=16, verbose_name='Card_number'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='exp_date',
            field=models.CharField(help_text='Buy exp_date', max_length=5, verbose_name='Exp_date'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
